### PR TITLE
Use checked instead of value for the classObject computed (Fix #3)

### LINKED ISSUE #3: Always `off` on `init`
I've used it in my project and it works fine. But it's initial view is not correct. I mean I've binded it as following:
`<vb-switch type="success" size="large" v-model="form.data.isActive"></vb-switch>`

But it is always `off` on init.

### PR DESCRIPTION
**Pull request by Elhebert**
Fix https://github.com/vue-bulma/switch/issues/3

### CODE REVIEW

**Comment by luventa** [comment]
Hi @Elhebert , did you test it with your change? Switch seems be disabled with your change.
I guess in computed method we shall still use `value` instead of `checked`. Could you please double check the functionality and rebase your commits? Thanks!

```
  computed: {
    classObject () {
      const { type, size, value } = this
      return {
        [`is-${type}`]: type,
        [`is-${size}`]: size,
        checked: value
      }
    }
  },
```

**Comment by Elhebert** [comment]
I did test my code, and the changes I made were the only way I had to make Switch to work properly.

As stated in https://github.com/vue-bulma/switch/issues/3 the Switch is not set on the correct value on initialisation. `this.value` was always false on initialisation (event if set to `this.checked` in a _beforeMount_ or _created_). Using this.checked solved that issue.

To be honest, we could even get rid of `this.value` here. It's useless, and I'll rework my code to remove it. Maybe it'll work properly for you too.

Because, a code that works only in certain "obscure" cases in not really good 😄

**Comment by luventa** [comment]
Hi @Elhebert. Yes, I agree with your point.
But when click switch element, the prop `check` does change while the `classObject` does not change. Thus, the visual effect does not works with your change.

So what I mentioned before `checked: value` will keep the computed prop `classObject` changing with correct logic.

I will merge your commits and make a quick fix for that. 

Thanks for your PR!

**Comment by Elhebert** [comment]
@luventa Actually, with the last changes I made, the computed `classObject` is always up to date with the checked props.

I'm not sure how to provide a demo for this (because I'll need webpack to compile it), but I can assure you it's working as intended :)

**Comment by luventa** [comment]
[vue-admin](https://github.com/vue-bulma/vue-admin) is using it as a demo and I tested your change on it. No worries I got it. Thanks for you time :D

**Pull request merged**
